/**
 * @file Tree-sitter grammar generated by monogram from a single CstGrammar.
 * @license MIT
 *
 * GENERATED — do not edit by hand. Regenerate from the source grammar.
 */

/// <reference types="tree-sitter-cli/dsl" />
// @ts-check

module.exports = grammar({
  name: "moon",

  extras: $ => [
    /\s/,
    $.line_comment,
    $.block_comment
  ],

  word: $ => $.identifier,

  externals: $ => [
    $.string_literal_chars,
    $.string_literal_variable,
    $.block_comment,
    $._statement_end,
    $._brace_end
  ],

  conflicts: $ => [
    [$.use_leaf, $.use_declaration],
    [$.name, $.expr],
    [$.name, $.loop_label],
    [$.name, $.named_type],
    [$.name, $.named_type, $.expr],
    [$.name, $.named_type, $.loop_label],
    [$.name, $.type],
    [$.expr, $.lvalue],
    [$.expr, $.expression_statement],
    [$.expression_statement],
    [$.named_type],
    [$.pattern],
    [$.break_statement],
    [$.continue_statement],
    [$.return_statement],
    [$.expr],
    [$.expr, $.block],
    [$.type],
    [$.type, $.expr],
    [$.type, $.expr, $.block],
  ],

  rules: {
    program: $ => repeat($.item),

    primitive_type: $ => choice("int", "float", "bool", "string", "void"),

    numeric_width_type: $ => choice("i8", "u8", "i16", "u16", "i32", "u32", "i64", "u64", "f16", "f32"),

    name: $ => choice($.identifier, $.primitive_type),

    binding_name: $ => choice($.identifier, "err"),

    function_name: $ => $.name,

    method_name: $ => choice($.name, "let", "ok", "err", "some", "none"),

    field_name: $ => choice($.identifier, "as", "async", "await", "break", "const", "continue", "defer", "else", "enum", "err", "errdefer", "extern", "false", "fn", "for", "if", "impl", "in", "interface", "let", "match", "mut", "none", "ok", "pub", "return", "some", "struct", "true", "type", "use", "while", $.primitive_type),

    include_path: $ => seq("<", repeat1(choice($.name, ".", "/", "-", "_")), ">"),

    named_type: $ => choice(seq($.identifier, repeat(seq(".", $.name)), "<", optional(seq($.type, repeat(seq(",", $.type)), optional(","))), optional(","), ">"), seq($.identifier, repeat(seq(".", $.name)))),

    type: $ => choice($.primitive_type, $.numeric_width_type, $.named_type, seq("*", optional("mut"), $.type), seq("fn", "(", optional(seq($.type, repeat(seq(",", $.type)), optional(","))), optional(","), ")", "->", $.type), seq("[", $.type, "]"), seq("{", $.type, ":", $.type, "}"), seq("(", optional(seq($.type, repeat(seq(",", $.type)), optional(","))), optional(","), ")"), seq($.type, "?")),

    type_parameters: $ => seq("<", optional(seq($.type_parameter, repeat(seq(",", $.type_parameter)), optional(","))), optional(","), ">"),

    type_parameter: $ => seq($.identifier, optional(seq(":", $.identifier, repeat(seq("+", $.identifier))))),

    return_type: $ => seq("->", $.type),

    parameter: $ => choice(seq($.binding_name, ":", optional("..."), $.type, optional(seq("=", $.expr))), seq(optional("mut"), $.identifier)),

    parameter_list: $ => seq("(", optional(seq($.parameter, repeat(seq(",", $.parameter)), optional(","))), optional(","), ")"),

    extern_parameter: $ => seq($.identifier, ":", $.type),

    extern_parameter_list: $ => seq("(", choice("...", seq($.extern_parameter, repeat(seq(",", $.extern_parameter)), optional(seq(",", "...")), optional(",")), blank()), ")"),

    pattern: $ => choice("_", "none", $.name, seq($.identifier, "@", $.pattern), seq("mut", $.name), seq("mut", $.identifier, "@", $.pattern), seq(choice("some", "ok", "err"), optional(seq("(", optional(seq($.pattern, repeat(seq(",", $.pattern)), optional(","))), optional(","), ")"))), $.integer, seq("-", $.integer), $.float, "true", "false", $.string_literal, seq(optional("-"), $.integer, choice("..", "..="), optional("-"), $.integer), seq($.string_literal, ".."), seq("..", $.string_literal, optional("..")), seq("(", optional(seq($.pattern, repeat(seq(",", $.pattern)), optional(","))), optional(","), ")"), seq($.identifier, "{", optional(seq($.struct_pattern_item, repeat(seq(",", $.struct_pattern_item)), optional(","))), optional(","), "}"), seq($.identifier, "(", optional(seq($.pattern, repeat(seq(",", $.pattern)), optional(","))), optional(","), ")"), seq($.qualified_variant, optional(seq("(", optional(seq($.pattern, repeat(seq(",", $.pattern)), optional(","))), optional(","), ")"))), seq(".", $.identifier, optional(seq("(", optional(seq($.pattern, repeat(seq(",", $.pattern)), optional(","))), optional(","), ")"))), seq("[", choice(seq(optional(seq($.pattern, repeat(seq(",", $.pattern)), optional(","))), optional(","), $.rest_pattern, optional(seq(",", optional(seq($.pattern, repeat(seq(",", $.pattern)), optional(","))))), optional(",")), seq(optional(seq($.pattern, repeat(seq(",", $.pattern)), optional(","))), optional(","))), "]")),

    qualified_variant: $ => seq($.identifier, repeat1(seq(".", $.identifier))),

    struct_pattern_item: $ => choice($.identifier, seq("mut", $.identifier), seq($.field_name, ":", $.pattern), choice("..", "...")),

    rest_pattern: $ => seq(choice("..", "..."), optional($.identifier)),

    argument: $ => seq(optional(seq($.identifier, choice(":", "="))), $.expr),

    call_arguments: $ => seq("(", optional(seq($.argument, repeat(seq(",", $.argument)), optional(","))), optional(","), ")"),

    struct_literal_item: $ => choice($.identifier, seq($.field_name, ":", $.expr), seq("...", $.expr)),

    dict_entry: $ => seq($.expr, optional("?"), ":", $.expr),

    for_clause: $ => seq("for", $.pattern, "in", $.expr),

    if_clause: $ => seq("if", $.expr),

    comprehension_clauses: $ => seq($.for_clause, repeat(choice($.for_clause, $.if_clause))),

    closure_parameter: $ => seq($.binding_name, optional(seq(":", $.type))),

    condition: $ => choice($.expr, seq("let", $.pattern, "=", $.expr)),

    match_arm: $ => seq($.pattern, repeat(seq("|", $.pattern)), optional(seq("if", $.expr)), "=>", choice($.expr, $.return_statement)),

    expr: $ => choice(
      prec.left(1, seq($.expr, field('operator', "||"), $.expr)),
      prec.left(2, seq($.expr, field('operator', "&&"), $.expr)),
      prec.left(3, seq($.expr, field('operator', choice("==", "!=", "|")), $.expr)),
      prec.left(4, seq($.expr, field('operator', choice("&", "^")), $.expr)),
      prec.left(5, seq($.expr, field('operator', choice("<", "<=", ">", ">=", "<<", ">>", ">>>", "..")), $.expr)),
      prec.left(6, seq($.expr, field('operator', choice("+", "-")), $.expr)),
      prec.left(7, seq($.expr, field('operator', choice("*", "/", "%")), $.expr)),
      prec.left(8, seq($.expr, field('operator', "as"), $.expr)),
      prec.right(9, seq(field('operator', choice("-", "!", "&", "*", "await")), $.expr)),
      "true",
      "false",
      "none",
      "some",
      "ok",
      "err",
      $.hex_integer,
      $.binary_integer,
      $.octal_integer,
      $.float,
      $.integer,
      $.string_literal,
      $.name,
      seq(".", $.identifier),
      prec.left(10, seq($.expr, "as", $.type)),
      prec.left(10, seq($.expr, $.call_arguments)),
      prec.left(10, seq($.expr, "<", optional(seq($.type, repeat(seq(",", $.type)), optional(","))), optional(","), ">", $.call_arguments)),
      prec.left(10, seq($.expr, ".", $.method_name, optional($.call_arguments))),
      prec.left(10, seq($.expr, ".", $.integer)),
      prec.left(10, seq($.expr, "[", $.expr, "]")),
      prec.left(10, seq($.expr, "?")),
      seq("(", ")"),
      seq("(", $.expr, ")"),
      seq("(", $.expr, ",", optional(seq($.expr, repeat(seq(",", $.expr)), optional(","))), optional(","), ")"),
      seq("{", repeat($.statement), optional($.expr), "}"),
      seq("if", $.condition, $.block, optional(seq("else", choice($.expr, $.block)))),
      seq("match", $.expr, "{", repeat(seq($.match_arm, optional(","))), "}"),
      seq("[", optional(seq($.expr, repeat(seq(",", $.expr)), optional(","))), optional(","), "]"),
      seq("[", $.expr, $.comprehension_clauses, "]"),
      seq("{:", "}"),
      seq("{", optional(seq($.dict_entry, repeat(seq(",", $.dict_entry)), optional(","))), optional(","), "}"),
      seq("{", $.expr, ":", $.expr, $.comprehension_clauses, "}"),
      seq("(", $.expr, $.comprehension_clauses, ")"),
      seq("||", optional($.return_type), $.expr),
      seq("|", optional(seq($.closure_parameter, repeat(seq(",", $.closure_parameter)), optional(","))), optional(","), "|", optional($.return_type), $.expr),
      prec.dynamic(-1, seq($.identifier, repeat(seq(".", $.identifier)), "{", optional(seq($.struct_literal_item, repeat(seq(",", $.struct_literal_item)), optional(","))), optional(","), "}")),
      seq("some", "(", $.expr, optional(","), ")"),
      seq("ok", "(", $.expr, optional(","), ")"),
      seq("err", ".", $.identifier, optional(seq("(", $.expr, optional(","), ")")))
    ),

    lvalue: $ => choice($.name, "some", "ok", "err", seq("*", $.expr), seq($.lvalue, ".", $.method_name), seq($.lvalue, "[", $.expr, "]")),

    assignment_operator: $ => choice("=", "+=", "-=", "*=", "/=", "%=", "&=", "|=", "^=", "<<=", ">>=", ">>>="),

    let_statement: $ => seq("let", optional("mut"), $.pattern, optional(seq(":", $.type)), "=", $.expr, optional(seq("else", $.block)), choice(";", $._statement_end, $._brace_end)),

    return_statement: $ => seq("return", optional($.expr), optional(";")),

    defer_statement: $ => choice(seq("defer", $.statement), seq("errdefer", $.statement)),

    loop_label: $ => seq($.identifier, ":"),

    while_statement: $ => seq(optional($.loop_label), "while", $.condition, $.block),

    for_statement: $ => seq(optional($.loop_label), "for", $.pattern, "in", $.expr, $.block),

    break_statement: $ => seq("break", optional($.identifier), optional(";")),

    continue_statement: $ => seq("continue", optional($.identifier), optional(";")),

    assignment_statement: $ => seq($.lvalue, $.assignment_operator, $.expr, choice(";", $._statement_end, $._brace_end)),

    expression_statement: $ => seq($.expr, choice(";", $._statement_end)),

    statement: $ => choice($.let_statement, $.return_statement, $.while_statement, $.for_statement, $.break_statement, $.continue_statement, $.defer_statement, $.assignment_statement, $.expression_statement),

    block: $ => seq("{", repeat($.statement), optional($.expr), "}"),

    visibility: $ => "pub",

    function_definition: $ => seq(optional($.visibility), optional(choice("async", "const")), "fn", $.function_name, optional($.type_parameters), $.parameter_list, optional($.return_type), $.block),

    extern_function: $ => seq(optional(seq("@", "blocking")), optional($.visibility), "extern", "fn", $.method_name, optional($.type_parameters), $.extern_parameter_list, optional($.return_type)),

    field: $ => seq($.field_name, ":", $.type),

    struct_definition: $ => seq(repeat(seq("@", choice("C", "packed"))), optional($.visibility), "struct", $.identifier, optional($.type_parameters), "{", optional(seq($.field, repeat(seq(",", $.field)), optional(","))), optional(","), "}"),

    variant: $ => seq($.identifier, optional(seq("(", optional(seq($.type, repeat(seq(",", $.type)), optional(","))), optional(","), ")")), optional(seq("=", $.string_literal))),

    enum_definition: $ => seq(optional($.visibility), "enum", $.identifier, optional($.type_parameters), "{", optional(seq($.variant, repeat(seq(",", $.variant)), optional(","))), optional(","), "}"),

    type_alias: $ => seq(optional($.visibility), "type", $.identifier, optional($.type_parameters), "=", $.type),

    const_definition: $ => seq(optional($.visibility), choice(seq("let", optional("mut")), "const"), $.identifier, optional(seq(":", $.type)), "=", $.expr),

    use_leaf: $ => seq($.name, optional(seq("as", $.name))),

    use_tail: $ => choice("*", seq("{", optional(seq($.use_leaf, repeat(seq(",", $.use_leaf)), optional(","))), optional(","), "}")),

    use_declaration: $ => seq(optional($.visibility), "use", $.name, repeat(seq(".", $.name)), optional(choice(seq(".", $.use_tail), seq("as", $.name)))),

    interface_associated_type: $ => seq("type", $.identifier, optional(seq("=", $.type))),

    interface_method: $ => seq("fn", $.function_name, optional($.type_parameters), $.parameter_list, optional($.return_type), optional($.block)),

    interface_item: $ => choice($.interface_method, $.interface_associated_type),

    interface_definition: $ => seq(optional($.visibility), "interface", $.identifier, optional($.type_parameters), "{", repeat($.interface_item), "}"),

    impl_associated_type: $ => seq("type", $.identifier, "=", $.type),

    impl_method: $ => seq(repeat($.directive), optional($.visibility), optional(choice("async", "const")), "fn", $.function_name, optional($.type_parameters), $.parameter_list, optional($.return_type), $.block),

    impl_target: $ => choice($.identifier, $.primitive_type, seq("[", $.type, "]"), seq("{", $.type, ":", $.type, "}")),

    impl_definition: $ => seq("impl", optional($.type_parameters), choice(seq($.identifier, "for", $.impl_target), $.impl_target), "{", repeat(choice($.impl_method, $.impl_associated_type)), "}"),

    directive_value: $ => choice($.string_literal, $.include_path, $.hex_integer, $.binary_integer, $.octal_integer, $.float, $.integer, "true", "false", seq($.name, repeat(seq(".", $.name)), optional(choice(seq("(", optional(seq($.directive_value, repeat(seq(",", $.directive_value)), optional(","))), optional(","), ")"), seq(":", $.directive_value))))),

    directive_arguments: $ => seq("(", optional(seq($.directive_value, repeat(seq(",", $.directive_value)), optional(","))), optional(","), ")"),

    directive: $ => seq("@", $.identifier, optional(choice($.directive_arguments, $.string_literal, $.include_path))),

    item: $ => choice($.function_definition, $.extern_function, $.struct_definition, $.enum_definition, $.type_alias, $.const_definition, $.use_declaration, $.interface_definition, $.impl_definition, $.directive),

    line_comment: $ => token(/\/\/[^\n]*/),


    identifier: $ => token(/[a-zA-Z_][a-zA-Z_0-9]*/),

    hex_integer: $ => token(/0x[0-9a-fA-F]+(?:_?[0-9a-fA-F])*/),

    binary_integer: $ => token(/0b[01]+(?:_?[01])*/),

    octal_integer: $ => token(/0o[0-7]+(?:_?[0-7])*/),

    float: $ => token(/[0-9]+(?:_?[0-9])*(?:\.[0-9]+(?:_?[0-9])*(?:[eE][+\-]?[0-9]+(?:_?[0-9])*)?|[eE][+\-]?[0-9]+(?:_?[0-9])*)/),

    integer: $ => token(/[0-9]+(?:_?[0-9])*/),

    string_literal: $ => seq(
      "\"",
      repeat(choice($.string_literal_chars, $.string_literal_variable, $.string_literal_substitution)),
      "\""
    ),

    string_literal_substitution: $ => seq("${", $.expr, "}")
  }
});

// entry rule: program
