;; -----------------------------------------------------------------
;; Tree-sitter highlight queries generated by monogram.
;; Capture names follow the standard tree-sitter highlight vocabulary
;; (@keyword, @function, @type, @string, @property, @operator, …).
;; Inferred from rule SHAPES + the grammar's `scopes` section — the same
;; structural inference the TextMate generator uses.
;; -----------------------------------------------------------------

;; Bare identifier (lowest priority; specific patterns below win).
(identifier) @variable

;; Structural member / type-param / property-access captures.
(named_type (identifier) @type)
(type_parameter (identifier) @type)
(expr (method_name (name (identifier) @property)))
(extern_parameter (identifier) @variable.parameter (type))
(parameter (binding_name (identifier) @variable.parameter))
(closure_parameter (binding_name (identifier) @variable.parameter))
(function_definition (function_name (name (identifier) @function)))
(extern_function (method_name (name (identifier) @function)))
(interface_method (function_name (name (identifier) @function)))
(impl_method (function_name (name (identifier) @function.method)))
(struct_definition (identifier) @type)
(enum_definition (identifier) @type)
(interface_definition (identifier) @type.interface)
(type_alias (identifier) @type)
(field (field_name (identifier) @property))
(loop_label (identifier) @label)
(string_literal_variable) @variable
(directive (identifier) @keyword)
((identifier) @type.builtin
  (#any-of? @type.builtin "Error" "Range" "Future" "Optional" "Result" "Iterator" "NdArray"))

;; Literal token nodes.
(line_comment) @comment
(block_comment) @comment
(hex_integer) @number
(binary_integer) @number
(octal_integer) @number
(float) @number
(integer) @number
(string_literal_chars) @string
(string_literal "\"") @string
(string_literal_substitution "${") @punctuation.special
(string_literal_substitution "}") @punctuation.special

;; Well-known property names.
((identifier) @operator
  (#any-of? @operator "." ".=" ".."))

;; Keyword, operator, and punctuation literals.
[
  "interface" "continue" "errdefer" "blocking" "return" "struct" "extern" "packed"
  "match" "while" "break" "await" "const" "async" "defer" "else"
  "enum" "impl" "type" "for" "pub" "let" "mut" "if"
  "in" "fn" "_" "C"
] @keyword
[
  "use" "as"
] @keyword.import
[
  "string" "float" "bool" "void" "int" "i16" "u16" "i32"
  "u32" "i64" "u64" "f16" "f32" "i8" "u8"
] @type.builtin
[
  "false" "true" "some" "none" "err" "ok"
] @constant.builtin
[
  ">>>=" "<<=" ">>=" ">>>" "+=" "-=" "*=" "/="
  "%=" "&=" "|=" "^=" "&&" "||" "==" "!="
  "<=" ">=" "<<" ">>" "->" "=>" "=" "!"
  "<" ">" "+" "-" "*" "/" "%" "&"
  "|" "^" "?"
] @operator
[
  "(" ")" "{" "}" "[" "]"
] @punctuation.bracket
[
  "{:" "," ";" ":" "@"
] @punctuation.delimiter
