// Tree-sitter external scanner generated by monogram.
//
// COMPLETE — the regex-literal scan and the template-literal scan are both
// wired from the grammar's token hints (`regexContext` and `template`).
//
// All language-specific data below is DERIVED from the CstGrammar, not
// hardcoded: the regex flag chars and the template delimiters all come from
// the grammar's token hints.

#include "tree_sitter/parser.h"
#include "tree_sitter/alloc.h"
#include <string.h>
#include <wctype.h>

enum TokenType {
  STRING_LITERAL_CHARS,
  STRING_LITERAL_VARIABLE,
  BLOCK_COMMENT,
  STATEMENT_END,
};

// The scanner is stateless — tree-sitter's `valid_symbols` already encodes
// the parse context (inside a regex slot? inside a template span?), and the
// `${ … }` brace nesting is handled by the template_substitution rule in the
// CFG, so there is nothing to (de)serialize.
typedef struct { char unused; } Scanner;

void *tree_sitter_moon_external_scanner_create(void) {
  return ts_calloc(1, sizeof(Scanner));
}

void tree_sitter_moon_external_scanner_destroy(void *payload) {
  ts_free(payload);
}

unsigned tree_sitter_moon_external_scanner_serialize(void *payload, char *buffer) {
  (void)payload; (void)buffer;
  return 0;
}

void tree_sitter_moon_external_scanner_deserialize(void *payload, const char *buffer, unsigned length) {
  (void)payload; (void)buffer; (void)length;
}

static inline void advance(TSLexer *lexer) { lexer->advance(lexer, false); }
static inline void skip(TSLexer *lexer) { lexer->advance(lexer, true); }

// ── Template-literal scan ───────────────────────────────────────
// Scans the literal run of characters inside a template, stopping just
// before the closing delimiter or before an interpolation hole, so a
// `${ … }` hole re-enters the expression grammar (mirrors gen-lexer.ts's
// scanTemplateSpan). The closing delimiter, the hole opener, and the hole
// closer are ordinary anonymous tokens matched by the CFG.
//
// Template delimiters (derived from the grammar's template hint):
//   open        = "\""
//   interpOpen  = "${"
//   interpClose = "}"
static bool scan_template_chars(TSLexer *lexer) {
  const char open[] = {'"'};
  bool has_content = false;
  for (;;) {
    // Freeze the token end here; any char we merely PEEK past below (a hole
    // opener) is then excluded from the emitted token.
    lexer->mark_end(lexer);
    int32_t c = lexer->lookahead;
    if (c == 0) return false; // EOF — let the CFG report the unterminated template
    // Closing delimiter: stop before it (it is an anonymous token).
    if (c == open[0]) break;
    // Interpolation hole opener (interpOpen "${").
    if (c == '$') {
      advance(lexer); // past the opener's first char (peek)
      if (lexer->lookahead == '{') break; // a real hole opener
      has_content = true; // lone first char → literal text, keep scanning
      continue;
    }
    // Backslash escape: consume `\` + next so an escaped delimiter stays literal.
    if (c == '\\') {
      advance(lexer);
      if (lexer->lookahead != 0) advance(lexer);
      has_content = true;
      continue;
    }
    advance(lexer);
    has_content = true;
  }
  if (!has_content) return false; // zero-width: let `${` / closing delimiter match
  lexer->result_symbol = STRING_LITERAL_CHARS;
  return true; // token end already frozen by the last mark_end
}

// Moon block comments nest to arbitrary depth. This external token is the one
// target-specific adaptation Monogram's regular token IR cannot express.
static bool scan_block_comment(TSLexer *lexer) {
  while (lexer->lookahead == ' ' || lexer->lookahead == '\t' ||
         lexer->lookahead == '\n' || lexer->lookahead == '\r') {
    skip(lexer);
  }
  if (lexer->lookahead != '/') return false;
  advance(lexer);
  if (lexer->lookahead != '*') return false;
  advance(lexer);
  unsigned depth = 1;
  while (lexer->lookahead != 0) {
    if (lexer->lookahead == '/') {
      advance(lexer);
      if (lexer->lookahead == '*') {
        advance(lexer);
        depth++;
      }
      continue;
    }
    if (lexer->lookahead == '*') {
      advance(lexer);
      if (lexer->lookahead == '/') {
        advance(lexer);
        depth--;
        if (depth == 0) {
          lexer->result_symbol = BLOCK_COMMENT;
          lexer->mark_end(lexer);
          return true;
        }
      }
      continue;
    }
    advance(lexer);
  }
  return false;
}

// Preserve Moon's short string interpolation as a structural token too.
static bool scan_template_dollar(TSLexer *lexer, bool emit_variable) {
  if (lexer->lookahead != '$') return false;
  advance(lexer);
  if (lexer->lookahead == '{') return false;
  bool identifier = (lexer->lookahead >= 'a' && lexer->lookahead <= 'z') ||
                    (lexer->lookahead >= 'A' && lexer->lookahead <= 'Z') ||
                    lexer->lookahead == '_';
  if (identifier) {
    do {
      advance(lexer);
    } while ((lexer->lookahead >= 'a' && lexer->lookahead <= 'z') ||
             (lexer->lookahead >= 'A' && lexer->lookahead <= 'Z') ||
             (lexer->lookahead >= '0' && lexer->lookahead <= '9') ||
             lexer->lookahead == '_');
  }
  lexer->mark_end(lexer);
  lexer->result_symbol = identifier && emit_variable
    ? STRING_LITERAL_VARIABLE
    : STRING_LITERAL_CHARS;
  return true;
}

// Expression statements without semicolons end at a physical newline. Keeping this
// as a hidden Tree-sitter-only token preserves Moon's statement boundary
// without making newline significant to Monogram's other generated targets.
static bool scan_statement_end(TSLexer *lexer) {
  while (lexer->lookahead == ' ' || lexer->lookahead == '\t') skip(lexer);
  if (lexer->lookahead == '\r') {
    advance(lexer);
    if (lexer->lookahead == '\n') advance(lexer);
  } else if (lexer->lookahead == '\n') {
    advance(lexer);
  } else {
    return false;
  }
  lexer->mark_end(lexer);
  lexer->result_symbol = STATEMENT_END;
  return true;
}

bool tree_sitter_moon_external_scanner_scan(void *payload, TSLexer *lexer,
                                                          const bool *valid_symbols) {
  (void)payload;

  // Template chars run first: whitespace INSIDE a template is literal text,
  // so it must NOT be skipped (unlike the regex path below).
  if (valid_symbols[STRING_LITERAL_CHARS]) {
    if (lexer->lookahead == '$') {
      return scan_template_dollar(lexer, valid_symbols[STRING_LITERAL_VARIABLE]);
    }
    if (scan_template_chars(lexer)) return true;
  }

  if (valid_symbols[STATEMENT_END] && scan_statement_end(lexer)) return true;

  if (valid_symbols[BLOCK_COMMENT] && scan_block_comment(lexer)) return true;

  return false;
}
